# Generated by Django 4.0.6 on 2022-08-04 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('url_img', models.CharField(max_length=1000)),
                ('url_img_risadola', models.CharField(max_length=1000)),
                ('descricao', models.CharField(max_length=500)),
                ('descricao_odio', models.CharField(max_length=666)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_img_passiva', models.CharField(max_length=1000)),
                ('url_img_arma', models.CharField(max_length=1000)),
                ('url_img_um', models.CharField(max_length=1000)),
                ('url_img_dois', models.CharField(max_length=1000)),
                ('url_img_passiva_ativa', models.CharField(max_length=1000)),
                ('url_img_arma_ativa', models.CharField(max_length=1000)),
                ('url_img_um_ativa', models.CharField(max_length=1000)),
                ('url_img_dois_ativa', models.CharField(max_length=1000)),
                ('nome_passiva', models.CharField(default='Habilas', max_length=20)),
                ('nome_arma', models.CharField(default='Habilas', max_length=20)),
                ('nome_um', models.CharField(default='Habilas', max_length=20)),
                ('nome_dois', models.CharField(default='Habilas', max_length=20)),
                ('descricao_passiva', models.CharField(default='Habilidade massa', max_length=200)),
                ('descricao_arma', models.CharField(default='Habilidade massa', max_length=200)),
                ('descricao_um', models.CharField(default='Habilidade massa', max_length=200)),
                ('descricao_dois', models.CharField(default='Habilidade massa', max_length=200)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.personagem')),
            ],
        ),
    ]
